import { HandleOutput } from "../src";

const output = new HandleOutput()

output.createBox(`

    \\$_\\$rLorem ipsum dolor sit amet, consectetur adipiscing elit.\\$- Fusce auctor ex id efficitur iaculis. Aenean condimentum erat tincidunt tristique mattis. Aliquam nunc purus, feugiat sed elit eget, viverra porttitor felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed id lacus eget eros bibendum accumsan. Nunc at dui mauris. Suspendisse bibendum magna ac leo imperdiet ultricies. Duis scelerisque libero vitae massa iaculis, in imperdiet neque placerat. Phasellus tristique, libero sit amet porta faucibus, mi diam cursus lacus, quis sollicitudin urna augue et nisi. Integer ultrices egestas est quis tempus. Nunc posuere elementum lacus, quis tincidunt velit fermentum nec. Etiam at urna sapien. Pellentesque eget viverra lacus. Praesent tristique sapien a lorem lobortis, vitae luctus elit feugiat.
    
    Nulla elementum sapien ac orci rhoncus aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur auctor vestibulum molestie. Aliquam quis aliquam elit. Integer venenatis consequat neque sed congue. Curabitur mattis ac arcu laoreet ultrices. Duis in facilisis risus. Vivamus vitae dignissim velit. Donec nulla mauris, bibendum volutpat dolor bibendum, interdum consectetur risus. Pellentesque eleifend suscipit arcu, et placerat tellus rhoncus eget. Fusce elementum orci purus, id commodo dolor condimentum quis. Fusce congue vulputate odio tincidunt dictum. Vivamus at ligula et libero egestas finibus.
    
    Duis eu nisi non lectus pulvinar maximus vel at arcu. Integer dignissim quam sed bibendum posuere. Ut imperdiet purus ullamcorper elit tincidunt pulvinar. In auctor pretium quam semper tempus. Quisque auctor sodales lorem. Nullam urna metus, elementum volutpat arcu eget, cursus aliquam nisl. Morbi aliquet ut ante in condimentum. Duis rhoncus lacinia erat nec sagittis. Fusce aliquet fringilla est, quis pulvinar nulla consectetur eu. Nam rhoncus mollis sodales.
    
    Ut tincidunt mollis sollicitudin. Curabitur sagittis iaculis erat, tincidunt porttitor dui pellentesque ac. Fusce aliquet volutpat quam, cursus eleifend ipsum laoreet at. Vivamus auctor malesuada lectus ut commodo. Donec scelerisque commodo elementum. Aenean mollis dui eu sollicitudin ultricies. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque dictum ac eros in finibus. Vivamus eu libero neque. In hendrerit cursus ex non porttitor. Maecenas eleifend, odio eu rutrum molestie, nisi elit faucibus augue, id tristique dolor ipsum eget nisi.
    
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer rhoncus feugiat leo, vitae semper elit luctus quis. Etiam vel est nulla. Nunc non auctor tortor, vitae blandit erat. Maecenas nec ultricies elit, id condimentum diam. Suspendisse vulputate, risus in aliquet semper, nunc arcu mattis lacus, eu suscipit ipsum odio a mi. Sed a neque arcu. Aliquam sed aliquet dui, nec imperdiet erat. Proin nisl magna, vulputate at vehicula sit amet, malesuada nec velit. `)